BEGIN TRY
	DROP TABLE [dbo].[DIM_DATUM]
END TRY

BEGIN CATCH
	/*No Action*/
END CATCH

/**********************************************************************************/

CREATE TABLE	[dbo].[DIM_DATUM]
	(	PK_SK_DATE INT PRIMARY KEY NOT NULL, 
	    JAHR INT, -- Year value of Date stored in Row
		QUARTAL INT,
		MONAT_NR INT,
		MONAT_NAME VARCHAR(40),
		WOCHE_NR INT,
		WOCHENTAG_NAME VARCHAR(40),
		DATUM DATETIME,
		MOST_RECENT_DAY_LAG INT,
		MOST_RECENT_WEEK_LAG INT,
		MOST_RECENT_MONTH_LAG INT,
		MOST_RECENT_YEAR_LAG INT,
		DATUMSKLASSE VARCHAR(40),
		TAG_IM_JAHR INT,
		TAG_IM_QUARTAL INT,
		TAG_IM_MONAT INT,
		TAG_IN_WOCHE INT,
		WOCHENTAGART VARCHAR(40),
		FEIERTAG_CH_J_N VARCHAR(40),
		SPRACHE CHAR(2),
		AUDIT_INS_DATE DATETIME,
		AUDIT_INS_NR INT,
		AUDIT_UPD_DATE DATETIME,
		AUDIT_UPD_NR INT,
		SORTIERUNG INT
	)
GO