USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT]    Script Date: 2/14/2018 12:45:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT](
	[ERROR_EVENT_KEY] [bigint] NOT NULL,
	[EVENT_DATE_FK] [int] NOT NULL,
	[DOMAIN_FK] [int] NOT NULL,
	[JOB_FK] [bigint] NOT NULL,
	[SCREEN_FK] [int] NOT NULL,
	[TOTAL_NUMBER_OF_ERRORS] [int] NULL,
	[DWH_INS_AUDIT_ID] [int] NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NULL,
 CONSTRAINT [FAK_ERROR_EVENT_PK] PRIMARY KEY CLUSTERED 
(
	[ERROR_EVENT_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT]  WITH CHECK ADD  CONSTRAINT [E_GLO_806_FAK_T906_ERROR_EVENT_E_GLO_806_DIM_T908_SCREEN_FK] FOREIGN KEY([SCREEN_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T908_SCREEN] ([SCREEN_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT] CHECK CONSTRAINT [E_GLO_806_FAK_T906_ERROR_EVENT_E_GLO_806_DIM_T908_SCREEN_FK]
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT]  WITH CHECK ADD  CONSTRAINT [ErrorEventFact_DIM_DATE_FK] FOREIGN KEY([EVENT_DATE_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T914_DATE] ([DATE_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT] CHECK CONSTRAINT [ErrorEventFact_DIM_DATE_FK]
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT]  WITH CHECK ADD  CONSTRAINT [ErrorEventFact_DIM_JOB_FK] FOREIGN KEY([JOB_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T912_TASK] ([TASK_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT] CHECK CONSTRAINT [ErrorEventFact_DIM_JOB_FK]
GO

