USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T913_LOG]    Script Date: 2/14/2018 12:47:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T913_LOG](
	[LOG_KEY] [bigint] NOT NULL,
	[JOB_FK] [bigint] NOT NULL,
	[SYSSSISLOG_FK] [int] NULL,
	[TEXT] [varchar](512) NOT NULL,
	[DWH_INS_AUDIT_ID] [int] NOT NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [LOG_PK] PRIMARY KEY CLUSTERED 
(
	[LOG_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_T913_LOG]  WITH CHECK ADD  CONSTRAINT [LOG_DIM_JOB_FK] FOREIGN KEY([JOB_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T912_TASK] ([TASK_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_T913_LOG] CHECK CONSTRAINT [LOG_DIM_JOB_FK]
GO

