USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T903_MAILGROUP]    Script Date: 2/14/2018 12:46:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T903_MAILGROUP](
	[MAILGROUP_KEY] [int] NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[DWH_INS_AUDIT_ID] [int] NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NULL,
 CONSTRAINT [MAILGROUP_PK] PRIMARY KEY CLUSTERED 
(
	[MAILGROUP_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

