USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T910_SETTING]    Script Date: 2/14/2018 12:46:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T910_SETTING](
	[SETTING_KEY] [int] NOT NULL,
	[DOMAIN_FK] [int] NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[VALUE] [varchar](256) NOT NULL,
 CONSTRAINT [SETTING_PK] PRIMARY KEY CLUSTERED 
(
	[SETTING_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_T910_SETTING]  WITH CHECK ADD  CONSTRAINT [DIM_DOMAIN_FK] FOREIGN KEY([DOMAIN_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T909_DOMAIN] ([DOMAIN_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_T910_SETTING] CHECK CONSTRAINT [DIM_DOMAIN_FK]
GO

