USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_DIM_T912_TASK]    Script Date: 2/14/2018 12:45:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_DIM_T912_TASK](
	[TASK_KEY] [bigint] NOT NULL,
	[DWH_JOB_FK] [int] NOT NULL,
	[MESSAGE_FK] [int] NOT NULL,
	[DOMAIN_FK] [int] NOT NULL,
	[START_DATETIME] [datetime] NOT NULL,
	[END_DATETIME] [datetime] NULL,
	[STATUS] [char](1) NOT NULL,
 CONSTRAINT [TASK_PK] PRIMARY KEY CLUSTERED 
(
	[TASK_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK]  WITH CHECK ADD  CONSTRAINT [DIM_DOMAIN_FKv2] FOREIGN KEY([DOMAIN_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T909_DOMAIN] ([DOMAIN_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK] CHECK CONSTRAINT [DIM_DOMAIN_FKv2]
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK]  WITH CHECK ADD  CONSTRAINT [DIM_JOB_FK] FOREIGN KEY([DWH_JOB_FK])
REFERENCES [dbo].[E_GLO_806_DIM_T911_JOB] ([JOB_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK] CHECK CONSTRAINT [DIM_JOB_FK]
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK]  WITH CHECK ADD  CONSTRAINT [DIM_MESSAGE_FK] FOREIGN KEY([MESSAGE_FK])
REFERENCES [dbo].[E_GLO_806_T904_MESSAGE] ([MESSAGE_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_DIM_T912_TASK] CHECK CONSTRAINT [DIM_MESSAGE_FK]
GO

