USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_DIM_T914_DATE]    Script Date: 2/14/2018 12:45:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_DIM_T914_DATE](
	[DATE_KEY] [int] NOT NULL,
	[DATUM_DATE] [date] NOT NULL,
	[TAG_NR] [int] NOT NULL,
	[WOCHENTAG_NR] [int] NOT NULL,
 CONSTRAINT [DIM_DATE_PK] PRIMARY KEY CLUSTERED 
(
	[DATE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

