USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_DIM_T909_DOMAIN]    Script Date: 2/14/2018 12:44:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_DIM_T909_DOMAIN](
	[DOMAIN_KEY] [int] NOT NULL,
	[ID] [int] NOT NULL,
	[ABBREVIATION] [varchar](10) NOT NULL,
	[NAME] [varchar](256) NULL,
 CONSTRAINT [DOMAIN_PK] PRIMARY KEY CLUSTERED 
(
	[DOMAIN_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

