USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T907_ERROR_DETAIL]    Script Date: 2/14/2018 12:46:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T907_ERROR_DETAIL](
	[ERROR_DETAIL_KEY] [bigint] NOT NULL,
	[ERROR_EVENT_FK] [bigint] NOT NULL,
	[ERROR_MESSAGE] [varchar](256) NOT NULL,
	[TABLE_NAME] [varchar](30) NULL,
	[COLUMN_NAME] [varchar](30) NULL,
	[RECORD_IDENTIFIER] [int] NOT NULL,
 CONSTRAINT [ERROR_DETAIL_PK] PRIMARY KEY CLUSTERED 
(
	[ERROR_DETAIL_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_T907_ERROR_DETAIL]  WITH CHECK ADD  CONSTRAINT [ERROR_DETAIL_FAK_ERROR_EVENT_FK] FOREIGN KEY([ERROR_EVENT_FK])
REFERENCES [dbo].[E_GLO_806_FAK_T906_ERROR_EVENT] ([ERROR_EVENT_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_T907_ERROR_DETAIL] CHECK CONSTRAINT [ERROR_DETAIL_FAK_ERROR_EVENT_FK]
GO

