USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_DIM_T911_JOB]    Script Date: 2/14/2018 12:44:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_DIM_T911_JOB](
	[JOB_KEY] [int] NOT NULL,
	[AUDIT_ID] [int] NOT NULL,
	[START_DATETIME] [datetime] NOT NULL,
	[END_DATETIME] [datetime] NULL,
	[STATUS] [char](1) NULL,
 CONSTRAINT [DIM_JOB_PK] PRIMARY KEY CLUSTERED 
(
	[JOB_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

