USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T905_LANGUAGE]    Script Date: 2/14/2018 12:46:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T905_LANGUAGE](
	[LANGUAGE_KEY] [int] NOT NULL,
	[ABBREVIATION] [char](3) NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[DWH_INS_AUDIT_ID] [int] NOT NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [LANGUAGE_PK] PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

