USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_DIM_T908_SCREEN]    Script Date: 2/14/2018 12:44:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_DIM_T908_SCREEN](
	[SCREEN_KEY] [int] NOT NULL,
	[DOMAIN_FK] [int] NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[DESCRIPTION] [varchar](256) NOT NULL,
	[ENABLED] [int] NOT NULL,
	[TYPE] [varchar](10) NOT NULL,
	[CALLER] [varchar](30) NOT NULL,
	[LAYER] [varchar](30) NOT NULL,
	[EXCEPTION_VIEW] [varchar](30) NOT NULL,
	[EXCEPTION_ACTION] [varchar](10) NOT NULL,
	[VALID_FROM_DATE] [date] NOT NULL,
	[VALID_TO_DATE] [date] NOT NULL,
	[MAX_ALLOWED_ERRORS] [int] NOT NULL,
	[TABLE_NAME] [varchar](80) NULL,
	[COLUMN_NAME] [varchar](80) NULL,
	[LOWER_LIMIT] [bigint] NULL,
	[UPPER_LIMIT] [bigint] NULL,
	[EXPECTED_VALUE] [bigint] NULL,
	[PERCENTAGE_DEVIATION] [smallint] NULL,
	[DWH_INS_AUDIT_ID] [int] NOT NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [DIM_SCREEN_PK] PRIMARY KEY CLUSTERED 
(
	[SCREEN_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

