USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_T901_USER]    Script Date: 2/14/2018 12:45:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_T901_USER](
	[USER_KEY] [int] NOT NULL,
	[USERNAME] [varchar](30) NOT NULL,
	[EMAIL] [varchar](30) NOT NULL,
	[AREA] [varchar](10) NULL,
	[LANGUAGE_FK] [int] NOT NULL,
	[DWH_INS_AUDIT_ID] [int] NOT NULL,
	[DWH_AUDIT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [USER_PK] PRIMARY KEY CLUSTERED 
(
	[USER_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_T901_USER]  WITH CHECK ADD  CONSTRAINT [LANGUAGE_FK] FOREIGN KEY([LANGUAGE_FK])
REFERENCES [dbo].[E_GLO_806_T905_LANGUAGE] ([LANGUAGE_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_T901_USER] CHECK CONSTRAINT [LANGUAGE_FK]
GO

