USE [SANDBOX]
GO

/****** Object:  Table [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP]    Script Date: 2/14/2018 12:43:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP](
	[USER_MAILGROUP_KEY] [int] NOT NULL,
	[USER_FK] [int] NOT NULL,
	[MAiLGROUP_FK] [int] NOT NULL,
	[DWH_INS_AUDIT_ID] [int] NOT NULL,
	[DWH_INS_AUDIT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [USER_MAILGROUP_PK] PRIMARY KEY CLUSTERED 
(
	[USER_MAILGROUP_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP]  WITH CHECK ADD  CONSTRAINT [F_GLO_806_BRG_T900_USER_MAILGROUP_F_GLO_806_T901_USER_FK] FOREIGN KEY([USER_FK])
REFERENCES [dbo].[E_GLO_806_T901_USER] ([USER_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP] CHECK CONSTRAINT [F_GLO_806_BRG_T900_USER_MAILGROUP_F_GLO_806_T901_USER_FK]
GO

ALTER TABLE [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP]  WITH CHECK ADD  CONSTRAINT [F_GLO_806_BRG_T900_USER_MAILGROUP_F_GLO_806_T903_MAILGROUP_FK] FOREIGN KEY([MAiLGROUP_FK])
REFERENCES [dbo].[E_GLO_806_T903_MAILGROUP] ([MAILGROUP_KEY])
GO

ALTER TABLE [dbo].[E_GLO_806_BRG_T900_USER_MAILGROUP] CHECK CONSTRAINT [F_GLO_806_BRG_T900_USER_MAILGROUP_F_GLO_806_T903_MAILGROUP_FK]
GO

